D.Suresh Roshi , 19PA1A0218 , EEE-A , II-I , AITTA

# Experiment No 1: Numpy

## 1.Different ways to create Numpy arrays.

In [2]:
import numpy as np
 
a = np.array([11,22,33,44,55])
print(a)

[11 22 33 44 55]


In [3]:
a = np.array([[11,22,33],[44,55,66]])
print(a)

[[11 22 33]
 [44 55 66]]


## 2.Add,remove,modify elements in an array.

In [4]:
a = np.arange(20)
b = np.append([21,22],a)
print(b)
b = np.append(a,[22,23])
print(b)

[21 22  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 22 23]


In [5]:
c = np.delete(a,[0])
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
d = np.array([11,22,33,44,55,66,77])
d[d<22]=-22
print(d)


[-22  22  33  44  55  66  77]


## 3.Arthematic operations on Numpy array.

In [7]:
import numpy as np

e = np.array([[1,3,5],[7,9,11]])
f = np.array([[10,2,4],[6,8,10]])

print(np.add(e,f))
print(np.subtract(e,f))
print(np.multiply(e,f))
print(np.divide(e,f))
print(np.mod(e,f))
print(np.power(e,f))


[[11  5  9]
 [13 17 21]]
[[-9  1  1]
 [ 1  1  1]]
[[ 10   6  20]
 [ 42  72 110]]
[[0.1        1.5        1.25      ]
 [1.16666667 1.125      1.1       ]]
[[1 1 1]
 [1 1 1]]
[[          1           9         625]
 [     117649    43046721 25937424601]]


## 4.Slicing and iterating of numpy arrays.

### i) Slicing.

In [8]:
import numpy as np
g = np.array([11,12,13,14,15,16,17,18,19])
print(g[2])
print(g[:5])
print(g[2:5])
print(g[2:-2])




13
[11 12 13 14 15]
[13 14 15]
[13 14 15 16 17]


### ii)Iterating.


In [9]:


h = np.arange(9).reshape(3,3)**3
print(h)
for i in h:
  print(i , end=" ")

[[  0   1   8]
 [ 27  64 125]
 [216 343 512]]
[0 1 8] [ 27  64 125] [216 343 512] 

## 5.Matrix operations on numpy arrays.

In [10]:
import numpy as np

i = np.array([[11,12,13],[14,15,16]])
j = np.array([[17,18,19],[11,12,13]])

print(np.add(i,j))
print(np.subtract(i,j))
print(np.multiply(i,j))
print(np.divide(i,j))
print(np.floor(i))
print(np.floor(j))

[[28 30 32]
 [25 27 29]]
[[-6 -6 -6]
 [ 3  3  3]]
[[187 216 247]
 [154 180 208]]
[[0.64705882 0.66666667 0.68421053]
 [1.27272727 1.25       1.23076923]]
[[11. 12. 13.]
 [14. 15. 16.]]
[[17. 18. 19.]
 [11. 12. 13.]]
